Movie_recommendation_system/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import index, star

urlpatterns = [
    path('admin/', admin.site.urls),  # 后台管理系统
    path('', index),  # 首页
    path('movie/', include('movie.urls')),  # 电影推荐系统子路由
]

movie/urls.py
from django.urls import path

from . import views

app_name = 'movie'

# 子路由
urlpatterns = [
    # 默认首页
    path('', views.IndexView.as_view(), name='index'),
    # 热门电影
    path('hot', views.PopularMovieView.as_view(), name='hot'),
    # 登录
    path('login', views.LoginView.as_view(), name='login'),
    # 退出
    path('logout', views.UserLogout, name='logout'),
    # 注册
    path('register', views.RegisterView.as_view(), name='register'),
    # 分类查看
    path('tag', views.TagView.as_view(), name='tag'),
    # 搜索功能
    path('search', views.SearchView.as_view(), name='search'),
    # 电影详情页面
    path('detail/<int:pk>', views.MovieDetailView.as_view(), name='detail'),
    # 评分历史页面
    path('history/<int:pk>', views.RatingHistoryView.as_view(), name='history'),
    # 删除记录
    path('del_rec/<int:pk>', views.delete_recode, name='delete_record'),
    # 推荐页面
    path('recommend', views.RecommendMovieView.as_view(), name='recommend')
]

movie/models.py
from django.db import models
from django.db.models import Avg


# 分类信息表
class Genre(models.Model):
    name = models.CharField(max_length=100, verbose_name="类型")

    class Meta:
        db_table = 'Genre'
        verbose_name = '电影类型'
        verbose_name_plural = '电影类型'

    def __str__(self):
        return self.name


# 电影信息表
class Movie(models.Model):
    name = models.CharField(max_length=256, verbose_name="电影名")
    imdb_id = models.IntegerField(verbose_name="imdb_id")
    time = models.CharField(max_length=256, blank=True, verbose_name="时长")
    genre = models.ManyToManyField(Genre, verbose_name="类型")
    release_time = models.CharField(max_length=256, blank=True, verbose_name="发行时间")
    intro = models.TextField(blank=True, verbose_name="简介")
    director = models.CharField(max_length=256, blank=True, verbose_name="导演")
    writers = models.CharField(max_length=256, blank=True, verbose_name="编剧")
    actors = models.CharField(max_length=512, blank=True, verbose_name="演员")
    # 电影和电影之间的相似度,A和B的相似度与B和A的相似度是一致的，所以symmetrical设置为True
    movie_similarity = models.ManyToManyField("self", through="Movie_similarity", symmetrical=False,
                                              verbose_name="相似电影")

    class Meta:
        db_table = 'Movie'
        verbose_name = '电影信息'
        verbose_name_plural = '电影信息'

    def __str__(self):
        return self.name

    # 获取平均分的方法
    def get_score(self):
        result_dct = self.movie_rating_set.aggregate(Avg('score'))  # 格式 {'score__avg': 3.125}
        try:
            result = round(result_dct['score__avg'], 1)  # 只保留一位小数
        except TypeError:
            return 0
        else:
            return result

    # 获取用户的打分情况
    def get_user_score(self, user):
        return self.movie_rating_set.filter(user=user).values('score')

    # 整数平均分
    def get_score_int_range(self):
        return range(int(self.get_score()))

    # 获取分类列表
    def get_genre(self):
        genre_dct = self.genre.all().values('name')
        genre_lst = []
        for dct in genre_dct.values():
            genre_lst.append(dct['name'])
        return genre_lst

    # 获取电影的相识度
    def get_similarity(self, k=5):
        # 默认获取5部最相似的电影的id
        similarity_movies = self.movie_similarity.all()[:k]
        return similarity_movies


# 电影相似度
class Movie_similarity(models.Model):
    movie_source = models.ForeignKey(Movie, related_name='movie_source', on_delete=models.CASCADE, verbose_name="来源电影")
    movie_target = models.ForeignKey(Movie, related_name='movie_target', on_delete=models.CASCADE, verbose_name="目标电影")
    similarity = models.FloatField(verbose_name="相似度")

    class Meta:
        # 按照相似度降序排序
        verbose_name = '电影相似度'
        verbose_name_plural = '电影相似度'


# 用户信息表
class User(models.Model):
    name = models.CharField(max_length=128, unique=True, verbose_name="用户名")
    password = models.CharField(max_length=256, verbose_name="密码")
    email = models.EmailField(unique=True, verbose_name="邮箱")
    rating_movies = models.ManyToManyField(Movie, through="Movie_rating")

    def __str__(self):
        return "<USER:( name: {:},password: {:},email: {:} )>".format(self.name, self.password, self.email)

    class Meta:
        db_table = 'User'
        verbose_name = '用户信息'
        verbose_name_plural = '用户信息'


# 电影评分信息表
class Movie_rating(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, unique=False, verbose_name="用户")
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, unique=False, verbose_name="电影")
    score = models.FloatField(verbose_name="分数")
    comment = models.TextField(blank=True, verbose_name="评论")

    class Meta:
        db_table = 'Movie_rating'
        verbose_name = '电影评分信息'
        verbose_name_plural = '电影评分信息'


# 最热门的一百部电影
class Movie_hot(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, verbose_name="电影名")
    rating_number = models.IntegerField(verbose_name="评分人数")

    class Meta:
        db_table = 'Movie_hot'
        verbose_name = '最热电影'
        verbose_name_plural = '最热电影'

# python manage.py makemigrations
# python manage.py migrate

movie/forms.py
from django import forms

from movie.models import User, Movie_rating


# 注册用的表单
class RegisterForm(forms.ModelForm):
    password_repeat = forms.CharField(max_length=256)

    def get_errors(self):
        errors = self.errors.get_json_data()
        errors_lst = []
        for messages in errors.values():
            for message_dict in messages:
                for key, message in message_dict.items():
                    if key == 'message':
                        errors_lst.append(message)
        return errors_lst

    # 普通验证之后的最后一层验证
    # 验证密码
    def clean(self):
        cleaned_data = super(RegisterForm, self).clean()
        pwd = cleaned_data.get('password')
        password_repeat = cleaned_data.get('password_repeat')
        if pwd != password_repeat:
            raise forms.ValidationError(message='两次密码输入不一致！')
        return cleaned_data

    class Meta:
        model = User
        fields = ['name', 'password', 'email']


# 登录的表单
class LoginForm(forms.ModelForm):
    name = forms.CharField(max_length=128)
    remember = forms.IntegerField(required=False)

    class Meta:
        model = User
        fields = ['password']

    def get_errors(self):
        errors = self.errors.get_json_data()
        errors_lst = []
        for messages in errors.values():
            for message_dict in messages:
                for key, message in message_dict.items():
                    if key == 'message':
                        errors_lst.append(message)
        return errors_lst


# 表单验证通过后再验证分数是否为0
class CommentForm(forms.ModelForm):
    def clean(self):
        cleaned_data = super(CommentForm, self).clean()
        score = cleaned_data.get('score')
        if score == 0:
            raise forms.ValidationError(message='评分不能为空！')
        else:
            return cleaned_data

    class Meta:
        # 电影评分，只记录评分和评论
        model = Movie_rating
        fields = ['score', 'comment']

movie/views.py
import os.path
import time

from django.contrib import messages
from django.db.models import Max, Count
from django.shortcuts import render, redirect, reverse
from django.views.generic import View, ListView, DetailView

from .forms import RegisterForm, LoginForm, CommentForm
from .models import User, Movie, Movie_rating, Movie_hot

BASE = os.path.dirname(os.path.abspath(__file__))


# 首页视图
class IndexView(ListView):
    model = Movie
    template_name = 'movie/index.html'
    paginate_by = 15
    context_object_name = 'movies'
    ordering = 'imdb_id'
    page_kwarg = 'p'

    # 返回前1000部电影
    def get_queryset(self):
        return Movie.objects.filter(imdb_id__lte=1000)

    # 获取上下文数据
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(IndexView, self).get_context_data(*kwargs)
        paginator = context.get('paginator')  # 分页器对象
        page_obj = context.get('page_obj')  # 当前页对象
        pagination_data = self.get_pagination_data(paginator, page_obj)  # 获取分页数据
        context.update(pagination_data)  # 返回更新后的上下文数据
        return context

    # 获取分页数据
    def get_pagination_data(self, paginator, page_obj, around_count=2):
        current_page = page_obj.number

        if current_page <= around_count + 2:
            left_pages = range(1, current_page)
            left_has_more = False
        else:
            left_pages = range(current_page - around_count, current_page)
            left_has_more = True

        if current_page >= paginator.num_pages - around_count - 1:
            right_pages = range(current_page + 1, paginator.num_pages + 1)
            right_has_more = False
        else:
            right_pages = range(current_page + 1, current_page + 1 + around_count)
            right_has_more = True
        return {
            'left_pages': left_pages,
            'right_pages': right_pages,
            'current_page': current_page,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more
        }


# 热门电影视图
class PopularMovieView(ListView):
    model = Movie_hot
    template_name = 'movie/hot.html'
    paginate_by = 15
    context_object_name = 'movies'
    page_kwarg = 'p'

    def get_queryset(self):
        # 初始化 计算评分人数最多的100部电影，并保存到数据库中，（不建议每次都运行）
        movies = Movie.objects.annotate(nums=Count('movie_rating__score')).order_by('-nums')[:100]
        for movie in movies:
            record = Movie_hot(movie=movie, rating_number=movie.nums)
            record.save()

        hot_movies = Movie_hot.objects.all().values("movie_id")
        movies = Movie.objects.filter(id__in=hot_movies).annotate(nums=Max('movie_hot__rating_number')).order_by(
            '-nums')
        return movies

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PopularMovieView, self).get_context_data(*kwargs)
        paginator = context.get('paginator')
        page_obj = context.get('page_obj')
        pagination_data = self.get_pagination_data(paginator, page_obj)
        context.update(pagination_data)
        return context

    def get_pagination_data(self, paginator, page_obj, around_count=2):
        current_page = page_obj.number

        if current_page <= around_count + 2:
            left_pages = range(1, current_page)
            left_has_more = False
        else:
            left_pages = range(current_page - around_count, current_page)
            left_has_more = True

        if current_page >= paginator.num_pages - around_count - 1:
            right_pages = range(current_page + 1, paginator.num_pages + 1)
            right_has_more = False
        else:
            right_pages = range(current_page + 1, current_page + 1 + around_count)
            right_has_more = True
        return {
            'left_pages': left_pages,
            'right_pages': right_pages,
            'current_page': current_page,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more
        }


# 电影分类视图
class TagView(ListView):
    model = Movie
    template_name = 'movie/tag.html'
    paginate_by = 15
    context_object_name = 'movies'
    page_kwarg = 'p'

    # 获取数据
    def get_queryset(self):
        # 未选择分类
        if 'genre' not in self.request.GET.dict().keys() or self.request.GET.dict()['genre'] == "":
            movies = Movie.objects.all()
            return movies[100:200]
        # 有分类选择
        else:
            movies = Movie.objects.filter(genre__name=self.request.GET.dict()['genre'])
            return movies[:100]

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TagView, self).get_context_data(*kwargs)
        if 'genre' in self.request.GET.dict().keys():
            genre = self.request.GET.dict()['genre']
            context.update({'genre': genre})
        paginator = context.get('paginator')
        page_obj = context.get('page_obj')
        pagination_data = self.get_pagination_data(paginator, page_obj)
        context.update(pagination_data)
        return context

    def get_pagination_data(self, paginator, page_obj, around_count=2):
        current_page = page_obj.number

        if current_page <= around_count + 2:
            left_pages = range(1, current_page)
            left_has_more = False
        else:
            left_pages = range(current_page - around_count, current_page)
            left_has_more = True

        if current_page >= paginator.num_pages - around_count - 1:
            right_pages = range(current_page + 1, paginator.num_pages + 1)
            right_has_more = False
        else:
            right_pages = range(current_page + 1, current_page + 1 + around_count)
            right_has_more = True
        return {
            'left_pages': left_pages,
            'right_pages': right_pages,
            'current_page': current_page,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more
        }


# 搜索电影视图
class SearchView(ListView):
    model = Movie
    template_name = 'movie/search.html'
    paginate_by = 15
    context_object_name = 'movies'
    page_kwarg = 'p'

    def get_queryset(self):
        movies = Movie.objects.filter(name__icontains=self.request.GET.dict()['keyword'])
        return movies

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(SearchView, self).get_context_data(*kwargs)
        paginator = context.get('paginator')
        page_obj = context.get('page_obj')
        pagination_data = self.get_pagination_data(paginator, page_obj)
        context.update(pagination_data)
        context.update({'keyword': self.request.GET.dict()['keyword']})
        return context

    def get_pagination_data(self, paginator, page_obj, around_count=2):
        current_page = page_obj.number

        if current_page <= around_count + 2:
            left_pages = range(1, current_page)
            left_has_more = False
        else:
            left_pages = range(current_page - around_count, current_page)
            left_has_more = True

        if current_page >= paginator.num_pages - around_count - 1:
            right_pages = range(current_page + 1, paginator.num_pages + 1)
            right_has_more = False
        else:
            right_pages = range(current_page + 1, current_page + 1 + around_count)
            right_has_more = True
        return {
            'left_pages': left_pages,
            'right_pages': right_pages,
            'current_page': current_page,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more
        }


# 注册视图
class RegisterView(View):
    def get(self, request):
        return render(request, 'movie/register.html')

    def post(self, request):
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('movie:index'))
        else:
            # 表单验证失败，重定向到注册页面
            errors = form.get_errors()
            for error in errors:
                messages.info(request, error)
            return redirect(reverse('movie:register'))


# 登录视图
class LoginView(View):
    def get(self, request):
        return render(request, 'movie/login.html')

    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data.get('name')
            pwd = form.cleaned_data.get('password')
            remember = form.cleaned_data.get('remember')
            user = User.objects.filter(name=name, password=pwd).first()
            if user:
                if remember:
                    # 设置为None，则表示使用全局的过期时间
                    request.session.set_expiry(None)
                else:
                    # 立即过期
                    request.session.set_expiry(0)
                # 登录成功，在session 存储当前用户的id，作为标识
                request.session['user_id'] = user.id
                return redirect(reverse('movie:index'))

            else:
                messages.info(request, '用户名或者密码错误!')
                return redirect(reverse('movie:login'))
        else:
            errors = form.get_errors()
            for error in errors:
                messages.info(request, error)
            return redirect(reverse('movie:login'))


# 登出，立即销毁session停止会话
def UserLogout(request):
    request.session.set_expiry(-1)
    return redirect(reverse('movie:index'))


# 电影详情视图
class MovieDetailView(DetailView):
    model = Movie
    template_name = 'movie/detail.html'
    # 上下文对象的名称
    context_object_name = 'movie'

    # 重写获取上下文方法，增加评分参数
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # 判断是否登录用
        login = True
        try:
            user_id = self.request.session['user_id']
        except KeyError as e:
            login = False  # 未登录

        # 获得电影的pk（这里pk就是id）
        pk = self.kwargs['pk']
        movie = Movie.objects.get(pk=pk)

        if login:
            # 已经登录，获取当前用户的历史评分数据

templates/movie/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="shortcut icon" href="{% static 'movie/favicon1.ico' %}"/>
    <link rel="bookmark" href="{% static 'movie/favicon1.ico' %}"/>
    <meta charset="UTF-8">
    <title>ZLab's Movie Recommender System</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
    <link rel="stylesheet" href="/static/bootstrap/js/jquery.min.js">
    <link rel="stylesheet" href="/static/bootstrap/js/bootstrap.min.js">

    <link rel="stylesheet" href="/static/css/bootstrap.min.css"><!--引入bootstrap的css样式库-->
    <script src="/static/js/jquery.min.js"></script><!--引入jQuery-->
    <!--bootstrap是基于jQuery库的，所以应该先导入jQuery-->
    <script src="/static/js/bootstrap.min.js"></script>


</head>
<body>
<!-- 导航条 -->
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'movie:index' %}">ZLab's Movie Recommender System</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'movie:index' %}">Home</a></li>
                <li><a href="{% url 'movie:tag' %}">Movie Categories</a></li>
                <li><a href="{% url 'movie:hot' %}">Popular Movies</a></li>
                {% if movie_user %}
                    <li><a href="{% url 'movie:recommend' %}">Recommended List</a></li>
                    <li><a href="{% url 'movie:history' movie_user.id %}">Rating History</a></li>
                {% endif %}
            </ul>
            <form class="navbar-form navbar-left" method="GET" action="{% url 'movie:search' %}">
                <div class="form-group">
                    <input type="search" name="keyword" class="form-control" placeholder="Input Movie's Information" required>
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                {% if movie_user %}
                    <li>
                        <div class="btn-group" style="margin-top:10px">
                            <button type="button" class="btn btn-info">{{ movie_user.name }}</button>
                            <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown"
                                    aria-haspopup="true" aria-expanded="false">
                                <span class="caret"></span>
                                <span class="sr-only">Toggle Dropdown</span>
                            </button>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'movie:logout' %}">Log Out</a></li>
                            </ul>
                        </div>
                    </li>
                {% else %}
                    <li><a href="{% url 'movie:register' %}">Sign Up</a></li>
                    <li><a href="{% url 'movie:login' %}">Log In</a></li>
                {% endif %}
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
{% block content %}

{% endblock %}


<div class="mastfoot" style="text-align: center;margin-top:50px;margin-bottom: 30px ">
    <div class="inner">
        <p>
            <span>Copyright (C). create by ZLab</span>&nbsp;&nbsp;
            <a href="/admin">Admin Login</a>
        </p>
    </div>
</div>

</body>
</html>

templates/movie/detail.html
{% extends 'movie/base.html' %}
{% block content %}

    <link href="http://netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://libs.baidu.com/jquery/1.10.2/jquery.min.js"></script>
    <link href="{% static 'css/star-rating.css' %}" media="all" rel="stylesheet" type="text/css"/>
    <script src="{% static 'js/star-rating.js' %}" type="text/javascript"></script>
    <style>
        .poster {
            float: left;
            margin: 3px 12px 0 0;
            overflow: hidden;
            text-align: center;
        }

        .info {
            max-width: 800px;
            margin-top: 15px;
            float: left;
            word-wrap: break-word;
        }

        .smovie {
            display: block;
            float: left;
            font-size: 15px;
            text-align: center;
            margin: 0 25px 10px 0;
            width: 200px;
        }

        hr {
            -moz-border-bottom-colors: none;
            -moz-border-image: none;
            -moz-border-left-colors: none;
            -moz-border-right-colors: none;
            -moz-border-top-colors: none;
            border-color: #c9302c;
            border-style: solid none;
            border-width: 1px 0;
            margin: 18px 0;
        }
    </style>
    <!--展示电影信息-->
    <div class="container">
        <div class="poster">
            <a href="{% url 'movie:detail' movie.pk %}" class="item">
                <div class="poster_div">
                    <img src="/static/movie/poster/{{ movie.imdb_id }}.jpg" alt="">
                </div>
            </a>
        </div>
        <div class="info">
            <p>
                Title：
                {{ movie.name }}
                <span>
                    {% for foo in movie.get_score_int_range %}
                        ❤
                    {% endfor %}
                </span>
                <strong style="color:#e09015">{{ movie.get_score }}</strong>
            </p>
            <p>Description：{{ movie.intro }}</p>
            <p>Director：{{ movie.director }}</p>
            <p>Writer：{{ movie.writers }}</p>
            <p>Main Cast：{{ movie.actors }}</p>
            <p>
                Genre：
                {% for genre in movie.get_genre %}
                    <a href="{% url 'movie:tag' %}?genre={{ genre }}">{{ genre }}</a>
                    {% if not forloop.last %}
                        <span>|</span>
                    {% endif %}
                {% endfor %}
            </p>
            <p>Duration：{{ movie.time }}</p>
            <p>Release Date：{{ movie.release_time }}</p>
        </div>
    </div>

    <div class="container similarity_movie">
        <br>
        <div class="alert alert-warning" role="alert">People who liked this movie also enjoyed...</div>

        {% for movie in similarity_movies %}
            <div class="smovie" {% if forloop.first %} style="margin-left: -6px" {% endif %}>
                <a href="{% url 'movie:detail' movie.pk %}" class="item">
                    <div class="poster_div">
                        <img src="/static/movie/poster/{{ movie.imdb_id }}.jpg" alt="">
                        <p>{{ movie.name }}
                            <strong style="color:#e09015">{{ movie.get_score }}</strong>
                        </p>
                    </div>
                </a>
            </div>

        {% endfor %}

    </div>

    <div class="container">
        <br>
        {% for message in messages %}
            {% if message.tags == 'info' %}
                <div class="alert alert-info" role="alert">{{ message }}</div>
            {% endif %}
        {% endfor %}
    </div>
    {% if login %}
        <div class="container">
            <hr>
            {#       利用js动态生成，依赖这个form#}
            <form class="star" action="" method="post">
                {#            评分组件#}
                <input id="input-2ba" name="score" value="{{ score }}" type="number" class="rating" min="0" max="5"
                       step="0.5"
                       data-stars=5
                       data-symbol="&#xe005;" data-default-caption="{rating} Likes" data-star-captions="{}">
                <label for="comment">Comment:</label>
                <textarea class="form-control" name="comment" rows="5" id="comment">{{ comment }}</textarea>
                <br>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary" style="margin-right: 10px">Submit</button>
                    <button type="reset" class="btn btn-default">Reset</button>
                </div>
            </form>
            <br>
            <script>
                jQuery(document).ready(function () {
                    $(".rating-kv").rating();
                });
            </script>
        </div>

    {% endif %}

{% endblock %}

templates/movie/history.html
{% extends 'movie/base.html' %}
{% block content %}
    <script src="{% static 'layer/layer.js' %}"></script>
    <style>
        .poster {
            float: left;
            margin: 3px 12px 0 0;
            overflow: hidden;
            text-align: center;
        }

        .info {
            margin-top: 15px;
            float: left;
            word-wrap: break-word;
        }

        hr {
            -moz-border-bottom-colors: none;
            -moz-border-image: none;
            -moz-border-left-colors: none;
            -moz-border-right-colors: none;
            -moz-border-top-colors: none;
            border-color: #c9302c;
            border-style: solid none;
            border-width: 1px 0;
            margin: 18px 0;
        }
    </style>
    <div class="container">
        {% for message in messages %}
            {% if message.tags == 'info' %}
                <div class="alert alert-success" role="alert">{{ message }}</div>
            {% endif %}
        {% endfor %}
        <div class="alert-success alert" role="alert">Rating History</div>
    </div>

    {% for rating in ratings %}
        <div class="container">
            <div class="poster">
                <a href="{% url 'movie:detail' rating.movie.pk %}" class="item">
                    <div class="poster_div">
                        <img src="/static/movie/poster/{{ rating.movie.imdb_id }}.jpg" alt="">
                    </div>
                </a>
            </div>
            <div class="info">
                <p>
                    Title：
                    {{ rating.movie.name }}
                    <span> <br>Average Rating Score：
                        {% for foo in rating.movie.get_score_int_range %}
                            ❤
                        {% endfor %}
                    </span>
                    <strong style="color:#e09015">{{ rating.movie.get_score }}</strong>
                </p>
                <p>Main Cast：{{ rating.movie.actors }}</p>
                <p>
                    Genre：
                    {% for genre in rating.movie.get_genre %}
                        <a href="{% url 'movie:tag' %}?genre={{ genre }}">{{ genre }}</a>
                        {% if not forloop.last %}
                            <span>|</span>
                        {% endif %}
                    {% endfor %}
                </p>
                <p>Duration：{{ rating.movie.time }}</p>
                <p>-------------------------------------------------------------------</p>
                <p>
                    My Rating Score：
                    <strong style="color:#e09015">{{ rating.score }} </strong><br>
                    My Comment：
                    <strong>{{ rating.comment }}</strong>
                </p>
                <button type="button" class="btn btn-warning"
                        onclick="confirm_delete('{% url "movie:delete_record" rating.movie.id %}')"><span
                        class="glyphicon glyphicon-trash"></span> Delete Comment
                </button>
            </div>

        </div>
        <div class="container">
            <hr>
        </div>

    {% endfor %}
    <script>
        // 删除文章的函数
        function confirm_delete(url) {
            // 调用layer弹窗组件
            layer.open({
                // 弹窗标题
                title: "确认删除",
                // 正文
                content: "确认删除这条评论吗？",
                // 点击确定按钮后调用的回调函数
                yes: function (index, layero) {
                    // 指定应当前往的 url
                    location.href = url
                },
            })
        }
    </script>
    <script>
        window.onkeyup = function (ev) {
            var key = ev.keyCode || ev.which;
            if (key == 27) { //按下Escape
                layer.closeAll(); //疯狂模式，关闭所有层
            }
        }
    </script>
{% endblock %}